FROM golang:1.21-alpine AS build_base

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o go-crud-template .


FROM build_base AS run-test-stage
RUN go test -v ./...


FROM ghcr.io/tailscale/golink:main 
FROM debian:stable-slim

WORKDIR /

COPY --from=build_base /app/go-crud-template .

EXPOSE 8080


ENTRYPOINT ["./go-crud-template"]
